img/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

# アプリケーション名
app_name = 'img'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('ajax', views.AjaxView.as_view(), name='ajax'),
    path('blog', views.BlogView.as_view(), name='blog'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imgsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('img.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('accounts/', include('allauth.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

img/models.py
from django.db import models

class Category(models.Model):
    category_name = models.CharField(verbose_name="カテゴリ名", max_length=100)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = "カテゴリテーブル"
        verbose_name_plural = "カテゴリテーブル"

class Blog(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(verbose_name="タイトル", max_length=200)
    image = models.ImageField(verbose_name="画像", upload_to='', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "ブログテーブル"
        verbose_name_plural = "ブログテーブル"

accounts/views.py
from django.shortcuts import render

# Create your views here.

img/views.py
# -*- coding: utf-8 -*-

import logging
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import TemplateView

from .models import Category
import db.db_connect as db
from .common import Common

class HomeView(TemplateView):
    """
    HOMEページ
    """

    # テンプレート名
    template_name = "home.html"

    def get(self, request):
        """
        HOMEページ初期表示処理
        """

        # テンプレートパラメータ
        params = {
        }
        return render(request, self.template_name, params)

class BlogView(TemplateView):
    """
    Blogページ
    """

    # テンプレート名
    template_name = "blog.html"

    def get(self, request):
        """
        Blogページ初期表示処理
        """
        # ログ出力
        logger = logging.getLogger('blog')

        # インスタンス生成
        common = Common()

        # カテゴリ一覧の取得
        category_list = common.get_category_list()

        # 独自SQLを実行
        sql = "select * from img_blog b inner join img_category c on b.category_id = c.id order by b.id"
        logger.debug(sql)
        blog_list = db.execute(sql)

        # テンプレートパラメータ
        params = {
            'selected_category': 0,
            'category_list': category_list,
            'blog_list': blog_list
        }
        return render(request, self.template_name, params)

    def post(self, request):
        """
        Blogページプルダウン変更処理
        """
        # ログ出力
        logger = logging.getLogger('blog')

        # インスタンス生成
        common = Common()

        # リクエストパラメータ取得
        category = request.POST.get('category')

        # カテゴリ一覧の取得
        category_list = common.get_category_list()

        # where句条件
        add_where = ""
        if category != '0':
            add_where = f"and b.category_id = { category }"

        # 独自SQLを実行
        sql = ("select * from img_blog b inner join img_category c on b.category_id = c.id "
               f"where 1=1 { add_where } "
               "order by b.id")
        logger.debug(sql)
        # SQL実行
        blog_list = db.execute(sql)

        # テンプレートパラメータ
        params = {
            'selected_category': int(category),
            'category_list': category_list,
            'blog_list': blog_list
        }
        return render(request, self.template_name, params)

class AjaxView(TemplateView):
    """
    Ajaxページ
    """

    # テンプレート名
    template_name = "ajax.html"

    def get(self, request):
        """
        Ajaxページ初期表示処理
        """

        # テンプレートパラメータ
        params = {
        }
        return render(request, self.template_name, params)

    def post(self, request):
        """
        Ajaxボタン押下処理
        """

        # ajaxパラメータ
        params = {
            'key1': 'value1',
            'key2': 'value2',
        }
        return JsonResponse(params)

templates/ajax.html
{# テンプレートのロード #}
{% extends "base.html" %}

{% block title %}
Ajax
{% endblock %}

{% block header %}
<h1>Ajaxサイトタイトル</h1>
{% endblock %}

{% block content %}
<div>
    <button id="button">ajax通信</button>
    <div id="result"></div>
</div>
{% endblock %}

{% block js %}
$(function(){
    $("#button").on('click', function(event) {
        $.ajax({
            type: "post",
            url: "{% url 'img:ajax' %}",
            dataType : "json"
        })
        // Ajaxリクエストが成功した場合
        .done(function(data) {
            console.log(data);
            $("#result").html(JSON.stringify(data));
        })
        // Ajaxリクエストが失敗した場合
        .fail(function(XMLHttpRequest, textStatus, errorThrown) {
            alert(errorThrown);
        });
    });
});
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="HandheldFriendly" content="True" />
        <meta name="csrf_token" content="{{ csrf_token }}">
        <title>
            {# 個別のタイトル #}
            {% block title %}
                {{ title }}
            {% endblock %}
        </title>
    </head>
    <body>
        <header>
            {# 個別のヘッダー #}
            {% block header %}
                {{ header }}
            {% endblock %}
        </header>

        <article>
            {# 個別のコンテツ #}
            {% block content %}
                {{ content }}
            {% endblock %}
        </article>

        <footer>
            <p>© サイトタイトル</p>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script>
            var csrftoken = $.cookie('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        </script>
        <script>
        {# 個別のJS #}
            {% block js %}
                {{ js }}
            {% endblock %}
        </script>
    </body>
</html>

templates/blog.html
{# テンプレートのロード #}
{% extends "base.html" %}

{% block title %}
Blog
{% endblock %}

{% block header %}
<h1>ブログサイトタイトル</h1>
<div>
    <form method="post" action="{% url 'img:blog' %}">
        {% csrf_token %}
        <select name="category" onchange="submit(this.form)">
            <option value="0"></option>
            {% for category in category_list %}
                <option value="{{ category.id }}" {% if category.id == selected_category %}selected{% endif %}>{{ category.id }}:{{ category.category_name }}</option>
            {% endfor %}
        </select>
    </form>
</div>
<div>
    <div>{{ blog_list|length }}件</div>
    <table>
        <thead>
            <tr>
                <th style="width:5rem;">カテゴリ</th>
                <th style="width:10rem;">タイトル</th>
                <th>画像</th>
            </tr>
        </thead>
        <tbody>
            {% for blog in blog_list %}
            <tr>
                <td>{{ blog.category_name }}</td>
                <td>{{ blog.title }}</td>
                <td><img src="/media/{{ blog.image }}" style="width:5rem;" /></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block content %}

{% endblock %}

templates/home.html
{# テンプレートのロード #}
{% extends "q/base.html" %}

{% load account %}

{% block title %}
Home
{% endblock %}

{% block header %}
<h1>サイトタイトル</h1>
{% endblock %}

{% block content %}
<div>
    <a href="{% url 'img:blog' %}">Blogページへ<a>
</div>
<div>
    <a href="{% url 'img:ajax' %}">Ajaxページへ<a>
</div>
<div>
    <div>ログインユーザ名:{% user_display user %}</div>
    <div>
        {% if user.is_authenticated %}
            ログイン中
        {% endif %}
    </div>
    <a href="{% url 'account_login' %}">ログインページへ<a>
    <br>
    <a href="{% url 'account_reset_password' %}">パスワードリセット<a>
    <br>
    <a href="{% url 'account_logout' %}">ログアウト</a>
</div>
{% endblock %}

templates/q/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="HandheldFriendly" content="True" />
        <meta name="csrf_token" content="{{ csrf_token }}">
        <title>
            {# 個別のタイトル #}
            {% block title %}
                {{ title }}
            {% endblock %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body>
        <header>
            {# 個別のヘッダー #}
            {% block header %}
                {{ header }}
            {% endblock %}
        </header>

        <article>
            {# 個別のコンテツ #}
            {% block content %}
                {{ content }}
            {% endblock %}
        </article>

        <footer>
            <p>© サイトタイトル</p>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script>
            var csrftoken = $.cookie('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        </script>
        <script>
            {% block js %}
                {{ js }}
            {% endblock %}
        </script>
    </body>
</html>

templates/q/blog.html
{# テンプレートのロード #}
{% extends "q/base.html" %}

{# タグライブラリ #}
{% load tags %}

{% block title %}
Blog
{% endblock %}

{% block header %}
<h1><a href="{% url 'img:q_blog' %}">QuerySet</a>ブログサイトタイトル</h1>
<div>
    -{{ selected_category }}-
    <br/>
    <form method="get" action="{% url 'img:q_blog' %}">
        <select name="category" onchange="submit(this.form)">
            <option value=""></option>
            {% for category in category_list %}
                <option value="{{ category.id }}" {% if category.id|num_to_str == selected_category %}selected{% endif %}>{{ category.id }}:{{ category.category_name }}</option>
            {% endfor %}
        </select>
    </form>
</div>
<div class="p-5">
    <div>{{ blog_list|length }}件</div>
    <table>
        <thead>
            <tr>
                <th style="width:5rem;">カテゴリ</th>
                <th style="width:10rem;">タイトル</th>
                <th>画像</th>
            </tr>
        </thead>
        <tbody>
            {% for blog in page_obj %}
            <tr>
                <td style="height:8rem;">{{ blog.category__category_name }}</td>
                <td>{{ blog.title }}</td>
                <td><img src="/media/{{ blog.image }}" style="width:5rem;" /></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div>
        {% include 'q/pagenation.html' %}
    </div>
</div>
{% endblock %}

{% block content %}

{% endblock %}

templates/q/home.html
{# テンプレートのロード #}
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block header %}
<h1>QuerySetサイトタイトル</h1>
{% endblock %}

{% block content %}
<div>
    <a href="{% url 'img:q_blog' %}">Blogページへ<a>
</div>
<div>
    <a href="{% url 'img:ajax' %}">Ajaxページへ<a>
</div>
{% endblock %}

templates/q/pagenation.html
{# タグライブラリ #}
{% load tags %}

{% if page_obj.has_previous %}
    <a class="btn btn-outline-primary mb-4" href="?page=1{{ request.GET.items|get_search_query_param }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" fill="currentColor" class="bi bi-skip-start" viewBox="0 0 16 16">
            <path d="M4 4a.5.5 0 0 1 1 0v3.248l6.267-3.636c.52-.302 1.233.043 1.233.696v7.384c0 .653-.713.998-1.233.696L5 8.752V12a.5.5 0 0 1-1 0V4zm7.5.633L5.696 8l5.804 3.367V4.633z"/>
        </svg>
    </a>
    <a class="btn btn-outline-primary mb-4" href="?page={{page_obj.previous_page_number}}{{ request.GET.items|get_search_query_param }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" fill="currentColor" class="bi bi-caret-left" viewBox="0 0 16 16">
            <path d="M10 12.796V3.204L4.519 8 10 12.796zm-.659.753l-5.48-4.796a1 1 0 0 1 0-1.506l5.48-4.796A1 1 0 0 1 11 3.204v9.592a1 1 0 0 1-1.659.753z"/>
        </svg>
    </a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
        <a class="btn btn-primary mb-4" href="?page={{num}}{{ request.GET.items|get_search_query_param }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-primary mb-4" href="?page={{num}}{{ request.GET.items|get_search_query_param }}">{{ num }}</a>
    {% endif %}
{% endfor %}

{% if page_obj.has_next %}
    <a class="btn btn-outline-primary mb-4" href="?page={{page_obj.next_page_number}}{{ request.GET.items|get_search_query_param }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" fill="currentColor" class="bi bi-caret-right" viewBox="0 0 16 16">
            <path d="M6 12.796V3.204L11.481 8 6 12.796zm.659.753l5.48-4.796a1 1 0 0 0 0-1.506L6.66 2.451C6.011 1.885 5 2.345 5 3.204v9.592a1 1 0 0 0 1.659.753z"/>
        </svg>
    </a>
    <a class="btn btn-outline-primary mb-4" href="?page={{page_obj.paginator.num_pages}}{{ request.GET.items|get_search_query_param }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" fill="currentColor" class="bi bi-skip-end" viewBox="0 0 16 16">
            <path d="M12.5 4a.5.5 0 0 0-1 0v3.248L5.233 3.612C4.713 3.31 4 3.655 4 4.308v7.384c0 .653.713.998 1.233.696L11.5 8.752V12a.5.5 0 0 0 1 0V4zM5 4.633L10.804 8 5 11.367V4.633z"/>
        </svg>
    </a>
{% endif %}